"""Filesystem-based project adapter implementation."""

from ros2_mcp.project.adapter import ProjectAdapter
from ros2_mcp.project.filesystem.safe_filesystem import SafeFilesystem


class FilesystemProjectAdapter(ProjectAdapter):
    """Create and manage ROS 2 project files inside an allowed root."""

    def __init__(self, filesystem: SafeFilesystem) -> None:
        """Create the adapter with restricted filesystem access."""
        self._filesystem = filesystem

    def create_workspace(self, workspace_path: str) -> dict[str, str]:
        """Create a ROS 2 workspace with a source directory."""
        workspace = self._filesystem.resolve_path(workspace_path)
        source_directory = workspace / "src"

        source_directory.mkdir(parents=True, exist_ok=True)

        return {
            "workspace": str(workspace),
            "src": str(source_directory),
        }

    def create_package(
        self,
        workspace_path: str,
        package_name: str,
    ) -> dict[str, str]:
        """Create a minimal ROS 2 Python package inside a workspace."""
        workspace = self._filesystem.resolve_path(workspace_path)
        source_directory = workspace / "src"
        package_directory = source_directory / package_name
        python_package_directory = package_directory / package_name
        resource_directory = package_directory / "resource"

        python_package_directory.mkdir(parents=True, exist_ok=True)
        resource_directory.mkdir(parents=True, exist_ok=True)

        package_xml = package_directory / "package.xml"
        setup_py = package_directory / "setup.py"
        pytest_ini = package_directory / "pytest.ini"
        resource_marker = resource_directory / package_name
        init_file = python_package_directory / "__init__.py"

        package_xml.write_text(
            f"""<?xml version="1.0"?>
<package format="3">
  <name>{package_name}</name>
  <version>0.0.0</version>
  <description>ROS 2 Python package generated by ros2-mcp.</description>
  <maintainer email="todo@example.com">TODO</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
"""
        )

        setup_py.write_text(
            f"""from glob import glob

from setuptools import find_packages, setup

package_name = "{package_name}"

setup(
    name=package_name,
    version="0.0.0",
    packages=find_packages(exclude=["test"]),
    data_files=[
        (
            "share/ament_index/resource_index/packages",
            ["resource/" + package_name],
        ),
        (
            "share/" + package_name,
            ["package.xml"],
        ),
        (
            "share/" + package_name + "/launch",
            glob("launch/*.launch.py"),
        ),
        (
            "share/" + package_name + "/config",
            glob("config/*.yaml"),
        ),
    ],
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="TODO",
    maintainer_email="todo@example.com",
    description="ROS 2 Python package generated by ros2-mcp.",
    license="TODO",
    tests_require=["pytest"],
    entry_points={{
        "console_scripts": [],
    }},
)
"""
        )

        pytest_ini.write_text(
            """[pytest]
testpaths = test
"""
        )

        resource_marker.touch(exist_ok=True)
        init_file.touch(exist_ok=True)

        return {
            "package": str(package_directory.resolve()),
            "python_package": str(python_package_directory.resolve()),
            "package_xml": str(package_xml.resolve()),
            "setup_py": str(setup_py.resolve()),
        }

    def create_node(
        self,
        workspace_path: str,
        package_name: str,
        node_name: str,
    ) -> dict[str, str]:
        """Create a Python ROS 2 node inside an existing package."""
        workspace = self._filesystem.resolve_path(workspace_path)
        package_directory = workspace / "src" / package_name
        python_package_directory = package_directory / package_name
        node_file = python_package_directory / f"{node_name}.py"

        if not python_package_directory.is_dir():
            raise FileNotFoundError(
                f"Python package does not exist: {python_package_directory}"
            )

        class_name = node_name.title().replace("_", "")

        node_file.write_text(
            f'''"""ROS 2 node generated by ros2-mcp."""

import rclpy
from rclpy.node import Node


class {class_name}(Node):
    """Minimal ROS 2 node."""

    def __init__(self) -> None:
        """Initialize the ROS 2 node."""
        super().__init__("{node_name}")


def main(args: list[str] | None = None) -> None:
    """Run the ROS 2 node."""
    rclpy.init(args=args)
    node = {class_name}()

    try:
        rclpy.spin(node)
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
'''
        )

        return {
            "node": str(node_file.resolve()),
            "package": str(package_directory.resolve()),
        }

    def create_launch_file(
        self,
        workspace_path: str,
        package_name: str,
        node_name: str,
        launch_name: str,
    ) -> dict[str, str]:
        """Create a Python launch file for an existing ROS 2 package."""
        workspace = self._filesystem.resolve_path(workspace_path)
        package_directory = workspace / "src" / package_name
        python_package_directory = package_directory / package_name

        if not python_package_directory.is_dir():
            raise FileNotFoundError(
                f"Python package does not exist: {python_package_directory}"
            )

        launch_directory = package_directory / "launch"
        launch_directory.mkdir(exist_ok=True)

        launch_file = launch_directory / f"{launch_name}.launch.py"

        launch_file.write_text(
            f'''"""Launch file generated by ros2-mcp."""

from launch import LaunchDescription
from launch_ros.actions import Node


def generate_launch_description() -> LaunchDescription:
    """Create the ROS 2 launch description."""
    return LaunchDescription(
        [
            Node(
                package="{package_name}",
                executable="{node_name}",
                name="{node_name}",
                output="screen",
            ),
        ]
    )
'''
        )

        return {
            "launch_file": str(launch_file.resolve()),
            "package": str(package_directory.resolve()),
        }

    def create_parameter_file(
        self,
        workspace_path: str,
        package_name: str,
        node_name: str,
        parameter_file_name: str,
    ) -> dict[str, str]:
        """Create a ROS 2 parameter YAML file for an existing package."""
        workspace = self._filesystem.resolve_path(workspace_path)
        package_directory = workspace / "src" / package_name
        python_package_directory = package_directory / package_name

        if not python_package_directory.is_dir():
            raise FileNotFoundError(
                f"Python package does not exist: {python_package_directory}"
            )

        config_directory = package_directory / "config"
        config_directory.mkdir(exist_ok=True)

        parameter_file = config_directory / f"{parameter_file_name}.yaml"

        parameter_file.write_text(
            f"""{node_name}:
  ros__parameters: {{}}
"""
        )

        return {
            "parameter_file": str(parameter_file.resolve()),
            "package": str(package_directory.resolve()),
        }

    def create_tests(
        self,
        workspace_path: str,
        package_name: str,
    ) -> dict[str, str]:
        """Create basic pytest tests for an existing ROS 2 package."""
        workspace = self._filesystem.resolve_path(workspace_path)
        package_directory = workspace / "src" / package_name
        python_package_directory = package_directory / package_name

        if not python_package_directory.is_dir():
            raise FileNotFoundError(
                f"Python package does not exist: {python_package_directory}"
            )

        test_directory = package_directory / "test"
        test_directory.mkdir(exist_ok=True)

        test_file = test_directory / "test_package_import.py"

        test_file.write_text(
            f'''"""Basic package import test generated by ros2-mcp."""


def test_package_import() -> None:
    """Verify that the generated ROS 2 Python package can be imported."""
    __import__("{package_name}")
'''
        )

        return {
            "test_file": str(test_file.resolve()),
            "package": str(package_directory.resolve()),
        }
